### ISSUE TITLE
Twitter Posting

### ISSUE THREAD

**Issue by rick165** [jim-easterbrook/pywws#115]
Is there any fix to the following error since twitter changed the api access?
:pywws.service.twitter:TwitterError([{u'message': u'You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product', u'code': 453}],)

**Comment by jim-easterbrook** [comment]
No, unless someone wants to pay Twitter $100 per month for pywws to be able to post messages.

**Comment by rick165** [comment]
I did wonder after it stopped working in July 23 and it hadn't been fixed yet. Shame really, oh well I'll post the stats on mastodon instead. Thanks for the feedback Jim, been using pywws for longer than I can remember 😊

**Comment by jim-easterbrook** [comment]
pywws has more than one user. If you create your own developer account and generate your own key/secret then you can post to Twitter. But if you share that key/secret (as pywws does) then all the users soon add up to more than 1000 posts per month.

**Comment by rick165** [comment]
Apologies, I'd always used pywws with my own twitter account in isolation.
