### ISSUE TITLE
FTP IOError No such file or directory: ... ftp.ini

### ISSUE THREAD

**Issue by emnullfuenf** [jim-easterbrook/pywws#26]
When enabling FTP in weather.ini i get the following error with pywws version 15.01.0:
...
File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1316, in _getstream = open(path, 'rb')
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/pywws/services/ftp.ini'

**Comment by jim-easterbrook** [comment]
On 25/05/15 17:47, emnullfuenf wrote:
> When enabling FTP in weather.ini i get the following error with pywws
> version 15.01.0:
> ...
> File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1316, in
> _getstream = open(path, 'rb')
> IOError: [Errno 2] No such file or directory:
> '/usr/local/lib/python2.7/dist-packages/pywws/services/ftp.ini'

I guess you are adding 'ftp' to your 'services' list. It isn't a service.

The results of your text and graph template processing are uploaded to
the FTP site you specify in weather.ini, unless you use a 'T' or 'L' flag.
http://pywws.readthedocs.org/en/latest/guides/weather_ini.html#ftp-configuration-of-uploading-to-a-website
-- 
Jim Easterbrook                 <http://www.jim-easterbrook.me.uk/>
