### ISSUE TITLE
livelog-daemon issue

### ISSUE THREAD

**Issue by kmckmc01** [jim-easterbrook/pywws#39]
Hi Jim,

I'm running pywws on Rpi jessie. All running well, apart from an issue running livelog-daemon. I get the following error:

 File "/usr/local/lib/python2.7/dist-packages/pywws/livelogdaemon.py", line 48, in <module>
    from daemon.runner import DaemonRunner
ImportError: No module named daemon.runner

Can you offer any advice on how to resolve?

Many thanks,

**Comment by jim-easterbrook** [comment]
Install the python-daemon package. See http://pywws.readthedocs.io/en/latest/essentials/dependencies.html#running-as-a-daemon
