### ISSUE TITLE
Allow start and stop to take the current year and month as parameters

### ISSUE THREAD

**Issue by PaulCheffus** [jim-easterbrook/pywws#40]
Hi

I am finding that showing the last 12 months means that the graph moves across the screen as the month progresses when I only use <duration>weeks = 52</duration>

Would it be possible in the plot to use the following syntax for start and stop
<stop>year=%Y, month=%m, day =31</stop>
Which would allow you to specify the stop date as the end of the current month. Obviously the number of days would need to be calculated but 31 could be used to indicate the end of the month.

Then the start date time would be 52 weeks prior which should stop the graph moving from right to left as the days in the month increase. It would only then move as the month changes.

The image below shows the issue
![capture](https://cloud.githubusercontent.com/assets/3186015/17144211/e711da26-534d-11e6-9e49-1044cb522bd1.PNG)

Cheers

Paul

**Comment by jim-easterbrook** [comment]
You can already set some elements of the <start> and <stop> values without introducing a new syntax.
http://pywws.readthedocs.io/en/latest/api/pywws.Plot.html#start
You could use this to set <stop> to day 28 of the current month, which would be safe.

**Comment by PaulCheffus** [comment]
Hi

I am currently trialing this but so far it hasn't made any difference.

Cheers

Paul
