### ISSUE TITLE
Please add support for candlesticks graphs

### ISSUE THREAD

**Issue by mbirth** [jim-easterbrook/pywws#42]
A candlesticks graph with whiskers (and/or whiskerbars) would be ideal for those day/night avg/max/min graphs currently used in 28days and yearly graphs.

Those look like these: http://gnuplot.sourceforge.net/demo/candlesticks.html . Or this one:

![image](https://cloud.githubusercontent.com/assets/130302/18292593/51361bd6-748e-11e6-8e6e-8aa436fcf0c7.png)

Sadly, the current source code doesn't allow this as candlesticks graphs need 4 y-values per row (NightAvg, NightMin, DayMax, DayAvg) and the Plot.py only writes 1 values per row.

I'm not sure but it might be sufficient if the `<ycalc>` field would allow a tuple to specify multiple data values. And the `using 1:2` string for gnuplot should be adapted accordingly.

**Comment by jim-easterbrook** [comment]
See CONTRIBUTING.rst for instructions on how to add a new feature and create a pull request.  (-:

**Comment by mbirth** [comment]
A little teaser. Pull request coming soon...

![2010c](https://cloud.githubusercontent.com/assets/130302/18405195/409ed768-76f0-11e6-97b7-b0b10cace40c.png)
