### ISSUE TITLE
MQTT Template in weather.ini being ignored

### ISSUE THREAD

**Issue by GeekyTim** [jim-easterbrook/pywws#69]
I have updated the MQTT template in weathwer.ini, and restarted pywws, but it is still sending out the old default template defined in mqtt.py.  For example, I don't have the temp_out_f, but it is still being received on the broker and subscribers.

**Comment by jim-easterbrook** [comment]
Is this after upgrading to commit 4ca8d5b or later? Earlier versions were ignoring template manipulation done after initialising the base class. Running at very high verbosity (run the class directly with 'python -m pywws.service.mqtt -vvvv data_dir') should print out the template.

**Comment by GeekyTim** [comment]
I'll upgrade again :-)

**Comment by jim-easterbrook** [comment]
If you haven't already done so, read this before running after upgrading.
https://groups.google.com/d/msg/pywws/5p6tP8Z9r0s/dLaisMGZAgAJ

**Comment by GeekyTim** [comment]
The update worked!  Thanks.

**Comment by jim-easterbrook** [comment]
Thanks for volunteering to test all this for me.  (-:

**Comment by GeekyTim** [comment]
No problem :-)

**Comment by GeekyTim** [comment]
multi-topic = True
retain = False

**Comment by jim-easterbrook** [comment]
No quotation marks or anything?

**Comment by GeekyTim** [comment]
No. Does it need them?

**Comment by jim-easterbrook** [comment]
No. But if they were there it explain your problem.

**Comment by jim-easterbrook** [comment]
As you have `multi_topic = True` I would expect you to see multi-topic messages when you monitor it. It doesn't stop the usual single topic message.

The `retain` value is passed to the mosquitto.Client session, so if it's being ignored that sounds like a bug in paho.mqtt.client.

**Comment by GeekyTim** [comment]
Ah! Misunderstood the multi-topic config.  That's working fine then :-)

retain does seem to be being ignored.  I'll look further.
