### ISSUE TITLE
Upload to Windy.com

### ISSUE THREAD

**Issue by mfraser** [jim-easterbrook/pywws#88]
Would like to be able to upload weather data to windy.com. They have an API at https://community.windy.com/topic/8168/report-you-weather-station-data-to-windy/35

**Comment by jim-easterbrook** [comment]
You can create your own "service" module, as described in https://pywws.readthedocs.io/en/latest/guides/integration.html#writing-your-own-uploader
Once you've got it working it'll be easy to add it to the pywws distribution.

**Comment by mfraser** [comment]
Any idea why this:
pywws.service.windy:server response "SUCCESS (partial) <br> unknown params: 'station_id', <br>"
is showing in the logs?

**Comment by jim-easterbrook** [comment]
I've just started testing the Windy uploader (after tweaking it a bit to make it more consistent with other service uploaders) and am getting the same `unknown params: 'station_id'` problem. This doesn't happen when running it from the command line, but does when doing live logging. The station id it's using is from the openweathermap service! Something very strange is happening, possibly related to multi-threading.

**Comment by jim-easterbrook** [comment]
Found it - service classes that don't define their own `fixed_data` end up sharing the one defined in the base class!
